version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: quantinfo
      POSTGRES_USER: quantinfo
      POSTGRES_PASSWORD: quantinfo123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://quantinfo:quantinfo123@postgres:5432/quantinfo
      REDIS_URL: redis://redis:6379
      CORS_ORIGINS: http://localhost:3000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host

  celery:
    build: ./backend
    command: celery -A celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://quantinfo:quantinfo123@postgres:5432/quantinfo
      REDIS_URL: redis://redis:6379
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: