openapi: 3.0.0
info:
  title: 股票信息采集系统 API
  version: 1.0.0
  description: 提供股票数据查询、技术分析和用户管理功能

servers:
  - url: http://localhost:8000/api/v1

paths:
  /auth/register:
    post:
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: 注册成功

  /auth/login:
    post:
      summary: 用户登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string

  /stocks:
    get:
      summary: 获取股票列表
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 股票列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Stock'
                  total:
                    type: integer
                  page:
                    type: integer

  /stocks/{symbol}:
    get:
      summary: 获取股票详情
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 股票详细信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockDetail'

  /stocks/{symbol}/history:
    get:
      summary: 获取股票历史数据
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
        - name: period
          in: query
          schema:
            type: string
            enum: [1d, 1w, 1m, 3m, 6m, 1y]
            default: 1m
      responses:
        '200':
          description: 历史价格数据

  /stocks/{symbol}/indicators:
    get:
      summary: 获取技术指标
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
        - name: indicators
          in: query
          schema:
            type: array
            items:
              type: string
              enum: [MA, EMA, RSI, MACD, BOLL]
      responses:
        '200':
          description: 技术指标数据

  /watchlist:
    get:
      summary: 获取自选股列表
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 用户自选股列表

    post:
      summary: 添加自选股
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
      responses:
        '201':
          description: 添加成功

components:
  schemas:
    Stock:
      type: object
      properties:
        symbol:
          type: string
        name:
          type: string
        price:
          type: number
        change:
          type: number
        changePercent:
          type: number
        volume:
          type: integer
        marketCap:
          type: number

    StockDetail:
      allOf:
        - $ref: '#/components/schemas/Stock'
        - type: object
          properties:
            high:
              type: number
            low:
              type: number
            open:
              type: number
            previousClose:
              type: number
            pe:
              type: number
            eps:
              type: number
            dividendYield:
              type: number

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT